-- =========================================================
-- Notas de Treino — estrutura no Supabase
--
-- Rode ESTE arquivo no mesmo projeto que já guarda o Foco.
-- Painel -> SQL Editor -> New query -> colar -> RUN.
--
-- Pode rodar mais de uma vez sem problema.
-- =========================================================


-- ---------------------------------------------------------
-- ROTINAS — um treino fixo por dia da semana
--
-- Os exercícios ficam num jsonb, igual estavam no Dexie:
--   [{ id, nome, categoria, seriesAlvo, observacao? }]
-- É a mesma forma que o app já usa, então nada muda no front.
-- ---------------------------------------------------------
create table if not exists public.rotinas (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null references auth.users(id) on delete cascade,
  dia_semana text        not null,
  nome       text        not null,
  exercicios jsonb       not null default '[]'::jsonb,
  criado_em  timestamptz not null default now()
);

create index if not exists rotinas_user_idx on public.rotinas (user_id);


-- ---------------------------------------------------------
-- SESSOES — a execução de uma rotina num dia
--
-- A unicidade (user, rotina, data) é o que faz
-- "abrir o treino de hoje" devolver sempre a mesma sessão
-- em vez de criar uma nova a cada clique.
-- ---------------------------------------------------------
create table if not exists public.sessoes (
  id         bigint generated by default as identity primary key,
  user_id    uuid    not null references auth.users(id) on delete cascade,
  rotina_id  bigint  not null references public.rotinas(id) on delete cascade,
  data       date    not null,
  finalizada boolean not null default false,
  unique (user_id, rotina_id, data)
);

create index if not exists sessoes_user_data_idx on public.sessoes (user_id, data desc);


-- ---------------------------------------------------------
-- EXECUCOES — o que você marcou em cada exercício
--
-- exercicio_id é o uuid que vive dentro do jsonb da rotina.
-- Não é chave estrangeira de propósito: se você renomear ou
-- reordenar um exercício, o histórico de carga continua
-- colado nele.
-- ---------------------------------------------------------
create table if not exists public.execucoes (
  id           bigint generated by default as identity primary key,
  user_id      uuid    not null references auth.users(id) on delete cascade,
  sessao_id    bigint  not null references public.sessoes(id) on delete cascade,
  exercicio_id text    not null,
  concluido    boolean not null default false,
  carga        numeric(7,2),
  reps_feitas  integer,
  unique (sessao_id, exercicio_id)
);

create index if not exists execucoes_sessao_idx    on public.execucoes (sessao_id);
create index if not exists execucoes_exercicio_idx on public.execucoes (user_id, exercicio_id);


-- =========================================================
-- SEGURANÇA (RLS)
--
-- Sem isto, qualquer pessoa com a publishable key lê o banco
-- inteiro. Com isto, o Postgres compara auth.uid() com
-- user_id em toda consulta e devolve só o que é seu.
-- =========================================================

alter table public.rotinas   enable row level security;
alter table public.sessoes   enable row level security;
alter table public.execucoes enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['rotinas','sessoes','execucoes'] loop
    execute format('drop policy if exists "%s: dono lê"       on public.%I', t, t);
    execute format('drop policy if exists "%s: dono insere"   on public.%I', t, t);
    execute format('drop policy if exists "%s: dono atualiza" on public.%I', t, t);
    execute format('drop policy if exists "%s: dono apaga"    on public.%I', t, t);

    execute format('create policy "%s: dono lê"       on public.%I for select using (auth.uid() = user_id)', t, t);
    execute format('create policy "%s: dono insere"   on public.%I for insert with check (auth.uid() = user_id)', t, t);
    execute format('create policy "%s: dono atualiza" on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)', t, t);
    execute format('create policy "%s: dono apaga"    on public.%I for delete using (auth.uid() = user_id)', t, t);
  end loop;
end $$;


-- =========================================================
-- Conferência: as três devem vir com rowsecurity = true
-- =========================================================
select tablename, rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename in ('rotinas','sessoes','execucoes');
